### PR TITLE
Add actionGetId() function in UserController

### PR DESCRIPTION
**Pull request by funkycram**
Missing documentation.

Enables to retreive User ID from username or email
Returns only the User ID (integer value)

METHOD : GET
URL : /api/v1/user/get-id
QUERY PARAMETERS : username (optional) or email (optional)

### CODE REVIEW

**Comment by luke-** [comment]
I would rather add two new endpoints:

`api/v1/user/get-by-email` and `api/v1/user/get-by-username`  which returning a full user info (same as ActionView).

Or is there a reason why only the ID should be returned?

**Comment by funkycram** [comment]
OK, I can change that.

The reason is that for User functions we need the User ID to execute an action on it.

So `api/v1/user/get-id` is for getting this ID when you don't have it and then execute the action in a second request.

I wait for your confirmation to return full user instead of only ID and I send a new pull request

**Comment by luke-** [comment]
I would really rather return a full user including ID instead of just the ID.

**Comment by funkycram** [comment]
OK, fine, I send a new pull request

**Pull request closed without merging**
