### PR TITLE
Check regular user access

### PR DESCRIPTION
**Pull request by yurabakhtin**
Add check permission for api modules:
or explain why we don't need it in some module:

- [x] Activity
- [x] Auth
- [x] Calendar
- [x] Cfiles
- [x] Comment
- [x] Content
- [x] File
- [x] Like
- [x] Mail
- [x] Notification
- [x] Post
- [x] Space
- [x] Tasks
- [x] Topic
- [x] User
- [x] Wiki

### CODE REVIEW

**Review by luke- — COMMENTED** [review]
Looks fine!

**Comment by yurabakhtin** [comment]
1. [√] User Module: check perms were added in https://github.com/humhub/humhub-modules-rest/pull/40/commits/7daac33fdb5f6166393fd834ce522149a793754a:
  1.1. User Controller => perm `\humhub\modules\admin\permissions\ManageUsers` because make sense to allow endpoints from these controller only for users who have similar access in back-office,
  1.2. Group Controller => perm `\humhub\modules\admin\permissions\ManageGroups` same reason as above,
  1.3. Session Controller => perm `\humhub\modules\admin\permissions\ManageUsers`, this controller has only an action to clear session data by user ID, so I think it should be allowed only for user who can manage other users from back-office as well.
  1.4. Invite Controller is not implemented.

**Comment by yurabakhtin** [comment]
2. [ ] Activity Module / Activity Controller: I don't see a reason to restrict any user for this module because it returns same data which are available for current User on front-office.
Yes @luke- wrote here https://github.com/humhub/tasks/issues/19#issuecomment-721721917:

> (Endpoints that have not yet implemented access checks should be at least marked as Admin Only.)

If someone doesn't agree please explain why we need restrict such data for similar api endpoints, thanks.

**Comment by yurabakhtin** [comment]
3\. [-] Auth Module: used for authorization and get data of current User, so no reason to check permissions here.

**Comment by luke-** [comment]
@yurabakhtin I like everything so far!

**Comment by yurabakhtin** [comment]
4\. [-] Calendar Module: This module looks completely broken because 10 endpoints are defined in route rules and documented here https://www.humhub.com/en/marketplace/rest/docs/html/calendar.html but I see only 3 actions are implemented in `controllers/calendar/CalendarController.php`.
We should either implement the missed endpoints or remove them from routing and from doc.

4.1. `actionRespond($id)` "Change the user participant" `/api/v1/calendar/entry/{id}/respond` => Error: "*Calling unknown method: humhub\\modules\\calendar\\models\\CalendarEntry::respond()"*".
4.2. `actionCreate($containerId)` "Create new calendar entry" `/api/v1/calendar/container/{containerId}` => Error: "*"Trying to get property 'time_zone' of non-object"*". But this action has a perm checking inside:
```
if (! $container->permissionManager->can(CreateEntry::class)) {
    return $this->returnError(403, 'You are not allowed to create calendar entry!');
}
```
4.3. `actionUpdate($id)` "Update calendar entry by id" `/api/v1/calendar/entry/{id}` => Error "*"Call to a member function getTimestamp() on bool"*". But this action has a perm checking inside:
```
if(! $calendarEntryForm->entry->content->canEdit()) {
    return $this->returnError(403, 'You are not allowed to update this calendar entry!');
}
```

**Comment by luke-** [comment]
@yurabakhtin Yes good point, `BaseContentController` should perform basic access checks. 

We have a https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/components/ActiveQueryContent.php#L46 which should be able handle the most cases.

As example just add `->readable()` here:
https://github.com/humhub/humhub-modules-rest/blob/master/components/BaseContentController.php#L68

```php
 $query = $class::find()->joinWith('content')->orderBy(['content.created_at' => SORT_DESC])->readable();
```

**Comment by luke-** [comment]
@yurabakhtin  The Endpoints modules are still in the REST API module for the following reasons:
- Base API not stable yet (e.g. `BaseContentController`)
- Documentation Generation (Dependencies, e.g. Calendar Module need Swagger definitions from REST Core)
- Documentation Publication (Each module has it's own REST Documentation, the REST Module of the HumHub Core) 

But once these issues are solved, we can put the REST APIs into the modules.

**Comment by yurabakhtin** [comment]
@luke- Commit https://github.com/humhub/humhub-modules-rest/pull/40/commits/67d298f1e582c04ae8b865989b2532b073f3c359 for proper checking on Calendar module and for `BaseContentController`

**Comment by yurabakhtin** [comment]
**5\. [-] CFiles** Module: added missed check perms in commit https://github.com/humhub/humhub-modules-rest/pull/40/commits/4bf8ec2df5a128ca248cdd3fdfabfff0c09e4540

**Comment by yurabakhtin** [comment]
**6\. [√] Comment** Module: added missed check perms in commit https://github.com/humhub/humhub-modules-rest/pull/40/commits/314243610d85b9fdbcb372911f3f6d36ee1b6713.

Note: It would be good to add an endpoint to Edit Comment because currently we have only View and Delete endpoints.

**Comment by yurabakhtin** [comment]
**7. [√] Content** Module: I added check perms in commit https://github.com/humhub/humhub-modules-rest/pull/40/commits/5f21d306bb7053832adbfd942dac4392dbaa541e, but this module looks not completed because there are 6 of 8 endpoints are commented, and only 2 of the 6 commented are implemented.
Also currently endpoint `/content/find-by-container/<id:\d+>` get all contents, code is here https://github.com/humhub/humhub-modules-rest/blob/enh/19-check-regular-user-access/controllers/content/ContentController.php#L28-L31:

```
$query = Content::find();
$query->andWhere(['contentcontainer_id' => (int) $id]);
$query->andWhere(['!=', 'object_model', Activity::class]);
$query->orderBy(['created_at' => SORT_DESC]);
```

but probably some content may be not allowed for some users and we should filter the query by `ContentActiveRecord->readable()` code like this:

```
$query = ContentActiveRecord::find($contentContainer->class);
$query->readable();
$query->andWhere(['contentcontainer_id' => (int) $id]);
$query->andWhere(['!=', 'object_model', Activity::class]);
$query->orderBy(['created_at' => SORT_DESC]);
```

Can someone confirm this?

**Comment by yurabakhtin** [comment]
**8. [√] File Module: ** commit https://github.com/humhub/humhub-modules-rest/pull/40/commits/9f877c0a3518eb07a4700ee58e1f312c02cc68bc

**Comment by yurabakhtin** [comment]
**9. [√] Like** Module: commit https://github.com/humhub/humhub-modules-rest/pull/40/commits/0ad2d2cbe6f83706708d17a5cd3134b92618dbd2

**Comment by yurabakhtin** [comment]
**10. [√] Mail** Module: commit https://github.com/humhub/humhub-modules-rest/pull/40/commits/fd4fd417d21976f61cb1d0604959cba89f11b375

**Comment by yurabakhtin** [comment]
**11. [√] Notification** Module: commit https://github.com/humhub/humhub-modules-rest/pull/40/commits/541a7477a12fe4c9101e4d12a7b8508e3e8de0b5

**Comment by yurabakhtin** [comment]
**12. [√] Post** Module is completely extended from `BaseContentController` which already has all proper check perms implemented in commit of the comment https://github.com/humhub/humhub-modules-rest/pull/40#issuecomment-724154953

**Comment by yurabakhtin** [comment]
**13. [√] Space** Module: commit https://github.com/humhub/humhub-modules-rest/pull/40/commits/bbe9264116fee6cf9b6ba2edd906f18783da3d73

Please note the method `\humhub\modules\space\behaviors\SpaceModelMembership->removeMember()` doesn't return `true` on success result, I didn't fix this because it is from another module, I just fixed condition to `if ($space->removeMember($userId) !== false) {` inside this current method rest api.

**Comment by yurabakhtin** [comment]
**14. [√] Tasks** Module:

1. `TaskListController` has no any restriction, i.e. any user can manage task lists of another user.
I think we should make `TaskList` extended from `ContentActiveRecord` in order to filter available records for current user by `ActiveQueryContent::readable()` as it is implemented e.g. for `Task`.
Either we should implement similar for `ContentContainer` because in api controllers the `ContentContainer::findOne()` is used many times so we should have something like `ContentContainer::find()->readable()->one()` or `if (!$contentContainer->canRead()) { return error }`.
2. `TasksController` already had all proper check permissions , but endpoint of creating new task has an issue in date/time formats with sample from postman fiel and doc page http://localhost:63342/humhub/protected/modules/humhub-modules-rest/docs/html/task.html?_ijt=qc5l23nru79vv4qvemhb07e9bk#tag/Task/paths/~1tasks~1container~1{id}/post:

```
"start_date": "2019-03-23",
"start_time": "10:00",
"end_date": "2019-03-25",
"end_time": "20:30",
```

I get the errors for each fields like "The format of {date/time} is invalid.", in order to avoid this error we may use:

```
"start_date": "2019-03-23 10:00:00",
"start_time": "10:00 AM",
"end_date": "2019-03-25 20:30:00",
"end_time": "8:30 PM",
```

if we will revert my change from here https://github.com/humhub/humhub-modules-rest/commit/67d298f1e582c04ae8b865989b2532b073f3c359#diff-f5664bf5d913b22bc39d96ad9533b5cc8a141232b698e5349d5e08a00ac1678dL291-L300 then we will can use the date fields in format `2019-03-23` but I did the fix because that code created a bug `Call to a member function getTimestamp() on bool` on creating/updating of Calendar Entry. I don't think we should revert my that fix, because it is not normal to require format like `2019-03-23 10:00:00` for data field and `10:00 AM` for time field. Probably we should change validators in `Task` class in order to accept at least date as `2019-03-23` and time as `20:30`.

**Comment by yurabakhtin** [comment]
**15. Topic** Module has check permission for all endpoints like:

```
if (Yii::$app->user->isAdmin()) {
    $topic = Topic::findOne($id);
} else {
    $topic = $this->getRelationTopicsQuery()->andWhere(['content_tag.id' => $id])->one();
}
```

I think this solution may be used for all other modules e.g. for model `TaskList` and `Content`.

**Comment by yurabakhtin** [comment]
**16. [√] Wiki** Module: commit https://github.com/humhub/humhub-modules-rest/pull/40/commits/94e76af3f609801cc41d07093d2f083a08b5d3b6

**Comment by luke-** [comment]
**Activity**:

I think we can also use `readable()` here.

e.g. https://github.com/humhub/humhub-modules-rest/blob/master/controllers/activity/ActivityController.php#L22
```php
Activity::find()
            ->readable()
            ->andWhere(['!=', 'created_by', Yii::$app->user->id])
 ```

**Comment by luke-** [comment]
**Comment** 
I've added an issue regarding the missing endpoints

**Content** 
Not sure if I understand it correctly. What do you mean  with "`6 of 8 endpoints are commented, and only 2 of the 6 commented are implemented`"?  But the added "Readable" is definitely good!

**Comment by luke-** [comment]
**Like** 

We should remove the camelCase here. Such a `find-by-record` is also required for the Comments & Files endpoint. Maybe `list`?

**Comment by luke-** [comment]
**Task**
Can you please create issues in the Tasks module for this? If security related please use our internal tracker `humhub/tasks`.

**Review by luke- — APPROVED** [review]
Looks very good, when it's ready to merge, we can release it as beta version e.g. 0.20.0-beta.1

**Comment by yurabakhtin** [comment]
@luke- 

> **Activity**:
> 
> I think we can also use `readable()` here.
> 
> e.g. https://github.com/humhub/humhub-modules-rest/blob/master/controllers/activity/ActivityController.php#L22
> 
> ```
> Activity::find()
>             ->readable()
>             ->andWhere(['!=', 'created_by', Yii::$app->user->id])
> ```

Thank you for the advice, I implemented this in commit https://github.com/humhub/humhub-modules-rest/pull/40/commits/cc5332e14f5e0937a00ce24dad43dc007222d289.

**Comment by yurabakhtin** [comment]
@luke- 

> **Content**
> Not sure if I understand it correctly. What do you mean with "`6 of 8 endpoints are commented, and only 2 of the 6 commented are implemented`"? But the added "Readable" is definitely good!

I meant here https://github.com/humhub/humhub-modules-rest/blob/enh/19-check-regular-user-access/Events.php#L77-L85:

```
// Content
['pattern' => 'api/v1/content/find-by-container/<id:\d+>', 'route' => 'rest/content/content/find-by-container', 'verb' => ['GET', 'HEAD']],
['pattern' => 'api/v1/content/container', 'route' => 'rest/content/container/list', 'verb' => 'GET'],
//['pattern' => 'api/v1/content/<id:\d+>', 'route' => 'api/user/content/view', 'verb' => ['GET', 'HEAD']],
//['pattern' => 'api/v1/content/', 'route' => 'api/user/content/delete', 'verb' => 'DELETE'],
//['pattern' => 'api/v1/content/pin/<id:\d+>', 'route' => 'api/user/content/pin', 'verb' => 'POST'],
//['pattern' => 'api/v1/content/unpin/<id:\d+>', 'route' => 'api/user/content/unpin', 'verb' => 'POST'],
//['pattern' => 'api/v1/content/archive/<id:\d+>', 'route' => 'api/user/content/archive', 'verb' => 'POST'],
//['pattern' => 'api/v1/content/unarchive/<id:\d+>', 'route' => 'api/user/content/unarchive', 'verb' => 'POST'],
```

we have 8 endpoints but 6 of 8 are commented out.
and in controllers I see only the following endpoints are implemented:
- `ContainerController::actionList()` => `GET:api/v1/content/container`
- `ContentController::actionFindByContainer($id)` => ???
- `ContentController::actionView($id)` => `GET:api/v1/content/<id:\d+>`
- `ContentController::actionDelete($id)` => `DELETE:api/v1/content/`

**Comment by yurabakhtin** [comment]
@luke- 

> **Like**
> 
> We should remove the camelCase here. Such a `find-by-record` is also required for the Comments & Files endpoint. Maybe `list`?

ok for now I changed to `find-by-record` in https://github.com/humhub/humhub-modules-rest/pull/40/commits/5e06be9bb276d091a224234a931faa2ce5310891, I am not sure `list` is good enough too because really the endpoint searches by columns `object_model` and `object_id` in the table `like`, so maybe `find-by-object` or `find-by-content`?

**Comment by yurabakhtin** [comment]
@luke- 

> **Task**
> Can you please create issues in the Tasks module for this? If security related please use our internal tracker `humhub/tasks`.

There is no security issue on Tasks module because e.g. to get Task List for editing in the module `tasks` the following code is used https://github.com/humhub/humhub-modules-tasks/blob/master/controllers/ListController.php#L86:

```
$taskList = TaskList::findById($id, $this->contentContainer);
```

but in the module `rest` no restriction by container - https://github.com/humhub/humhub-modules-rest/blob/master/controllers/tasks/TaskListController.php#L39:

```
$list = TaskList::findOne(['id' => $id]);
```

So any user can manage tasks lists of other users by API, we should implement same restriction only from API side, module `rest`.

**Comment by luke-** [comment]
**Like:** Then let's switch to **find-by-object** and use this naming also at other modules. e.g. at comments

**Content:** The commented out routes should show in the beginning how the finished API might look like later. However, it is important that the documentation is consistent with the actual implementation.

I think this two routes can be enabled?
```php 
            //['pattern' => 'api/v1/content/<id:\d+>', 'route' => 'api/user/content/view', 'verb' => ['GET', 'HEAD']],
            //['pattern' => 'api/v1/content/', 'route' => 'api/user/content/delete', 'verb' => 'DELETE'],
```

`ContentController::actionFindByContainer($id) => ??? (**GET: api/v1/content/find-by-container/<id:\d+>**)`

**Activity:**  Ok

**Tasks:** (I hope I have understood it completely.) If so, I think it would be good idea if we could find a generic way to load the ContentContainer and also check the access rights here. In addition, a check whether the module on the container is activated at all would also be good here. 

---

Otherwise, can I merge the PR or is something still open? I would then release a beta version and a customer is also waiting for the mail API.

**Review by luke- — APPROVED** [review]

**Comment by yurabakhtin** [comment]
@luke- 

> **Like:** Then let's switch to find-by-object and use this naming also at other modules. e.g. at comments

Commit https://github.com/humhub/humhub-modules-rest/pull/40/commits/77cf6f51d5fcfe0f4839fda741cf117210203590 only for "Like" module, I don't find where other modules use similar endpoints.

---

> **Content:** The commented out routes should show in the beginning how the finished API might look like later. However, it is important that the documentation is consistent with the actual implementation.
>
I think this two routes can be enabled?

Ok, I enabled them with small fixes - https://github.com/humhub/humhub-modules-rest/pull/40/commits/1c57b403f41a1f99a39425d7bf6de09b1c395831

But please note as I wrote in comment https://github.com/humhub/humhub-modules-rest/pull/40#issuecomment-724600656 the endpoint `/content/find-by-container/<id:\d+>` still has no restriction, i.e. any user can view the content records of another user I think, if it is ok for now then we can keep it as is.

---

> Tasks: (I hope I have understood it completely.) If so, I think it would be good idea if we could find a generic way to load the ContentContainer and also check the access rights here. In addition, a check whether the module on the container is activated at all would also be good here.

Yes, we should either find or implement some new `ContentContainer::find()->readable()` or `if (!$contentContainer->canRead()) { return error }`, so user will access only for allowed containers.

---

> Otherwise, can I merge the PR or is something still open? I would then release a beta version and a customer is also waiting for the mail API.

Yes, you can merge the changes, but as I wrote at least 2 modules "Content" and "Tasks" still need additional security restrictions.

**Review by luke- — APPROVED** [review]

**Comment by luke-** [comment]
**Like:** Yes, this should be the only case at the moment. In the future there will certainly be more `find-by-object` endpoints.

**Content:** Perfect! Maybe we can add a simple `$content->canRead()` for a first version release. Later we should add a besser  access check directly in the db query.

**Tasks:** 

Something like this

```php
$userGroupValidator = new UserGroupAccessValidator(['contentContainer' => $contentContainer]);
$userGroupValidator->validate([ContentContainerCotnrollerAccess::RULE_USER_GROUP_ONLY => [Space::USERGROUP_MEMBER]]);
``` 
or this:
```php
if ($container instanceof User && $container->id != Yii::$app->user->id) {
   return $this->returnError(400);
} elseif ($container instanceof Space && !$container->isMember(Yii::$app->user->id)) {
    return $this->returnError(400);
}
``` 
?

**Comment by yurabakhtin** [comment]
@luke- 

> **Content:** Perfect! Maybe we can add a simple `$content->canRead()` for a first version release. Later we should add a besser access check directly in the db query.

It is not good to use `$content->canRead()` after query was initialized and especially with pagination, so I implemented this by query in commit https://github.com/humhub/humhub-modules-rest/pull/40/commits/6c3f23ac825fb349ac3da7b1f24ad695442d6b12 with using `ActiveQueryContent->readable()`, of course my code looks like a hack because we don't need `joinWith('content')` from the `readable()` for Content model, maybe in future the `readable()` will be modified to don't call `joinWith('content')` if `$this->modelClass != 'humhub\modules\content\models\Content'`.

---

> **Tasks:**
>
> Something like this
> ...
```
if ($container instanceof User && $container->id != Yii::$app->user->id) {
   return $this->returnError(400);
} elseif ($container instanceof Space && !$container->isMember(Yii::$app->user->id)) {
    return $this->returnError(400);
}
```

I implemented this solution in commit https://github.com/humhub/humhub-modules-rest/pull/40/commits/bbcc5e93f0d0e18ceb3454d0c9a14107c81ae8da.

---

I think now all modules have check permission and this PR can be merged.

**Comment by luke-** [comment]
@yurabakhtin Nice solution with the `readable()` for Content records! :-)

**Pull request merged**
